### ISSUE TITLE
Pinned dry-types version

### ISSUE THREAD

**Issue by ehannes** [accodeing/fortnox-api#177]
`dry-types` is pinned to version < 0.13.0 due to breaking changes. See https://github.com/accodeing/fortnox-api/commit/1f446ef00dbd15fe7df1c33d997c394a8b883063. Unfortunately, I have no idea what the breaking changes is. But probably something we should fix sometime...

**Comment by mbirman** [comment]
See https://github.com/accodeing/fortnox-api/pull/157#discussion_r188680733
